In [23]:
import pandas as pd
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
# Baseline model name (or full path). Prefix with 'baseline:' to pull from
# results/whisper_baseline/whisper_baseline.csv
BASELINE = 'baseline:whisper'

# Comparison model names (without .csv) or full paths — one or more.
COMPARISON_MODELS = [
    'bridge_dtw_eps_0.5',
    'bridge_dtw_eps_0.5_odesampling',
    'bridge_position_eps_1.5',
    'bridge_dtw_fixed_eps_0.5',
    'bridge_dtw_fixed_eps_0.5_odesampling',
    # 'bridge_dtw_fixed_eps_0.5_antirep',
    'bridge_dtw_fixed_x0_0.5',
    # 'bridge_dtw_fixed_x0_0.5_antirep',
    'bridge_dtw_fixed_x0_0.5_odesampling',
]

# Metric that drives win/draw/loss classification and best/worst ranking.
PRIMARY_METRIC = 'utt_wer'

# Columns to show in comparison tables. Use None to show all shared metric columns.
SHOW_COLS = ['utt_wer']

# Number of rows to show in the best-wins / worst-losses tables.
TOP_N = 20

# Optional filters (set to None to skip) — applied to baseline and all comparison models
FILTER_L1 = None       # e.g. 'Hindi'
FILTER_SPEAKER = None  # e.g. 'THV'

# ── Path resolution ───────────────────────────────────────────────────────────
ROOT = Path("/vol/gpudata/tsv22-fyp/accent-robust-asr")
BRIDGE_DIR   = Path(f'{ROOT}/results/bridge_eval')
STEERING_DIR = Path(f'{ROOT}/results/e2_steering')
BASELINE_DIR = Path(f'{ROOT}/results/whisper_baseline')

def resolve(name: str) -> Path:
    if name.startswith('baseline:'):
        return BASELINE_DIR / 'whisper_baseline.csv'
    p = Path(name)
    if p.suffix == '.csv' and p.exists():
        return p
    for d in [BRIDGE_DIR, STEERING_DIR]:
        candidate = d / f'{name}.csv'
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f'Cannot find CSV for {name!r}')

path_baseline = resolve(BASELINE)
print(f'Baseline: {BASELINE} -> {path_baseline}')
for name in COMPARISON_MODELS:
    print(f'  {name} -> {resolve(name)}')

Baseline: baseline:whisper -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/whisper_baseline/whisper_baseline.csv
  bridge_dtw_eps_0.5 -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_dtw_eps_0.5.csv
  bridge_dtw_eps_0.5_odesampling -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_dtw_eps_0.5_odesampling.csv
  bridge_position_eps_1.5 -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_position_eps_1.5.csv
  bridge_dtw_fixed_eps_0.5 -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_dtw_fixed_eps_0.5.csv
  bridge_dtw_fixed_eps_0.5_odesampling -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_dtw_fixed_eps_0.5_odesampling.csv
  bridge_dtw_fixed_x0_0.5 -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_dtw_fixed_x0_0.5.csv
  bridge_dtw_fixed_x0_0.5_odesampling -> /vol/gpudata/tsv22-fyp/accent-robust-asr/results/bridge_eval/bridge_dtw_fixed_x0_0.5_odesampling.csv

In [24]:
NON_METRIC = {'utterance_id', 'speaker', 'l1', 'domain', 'wav_path', 'text',
              'prediction', 'reference_norm', 'prediction_norm', 'speaker_type',
              'bridge_split', '_label'}

def load(path: Path, label: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    # normalise column names across different eval scripts
    renames = {'wer': 'utt_wer', 'mer': 'utt_mer', 'per': 'utt_per',
               'whisper_pred': 'prediction', 'whisper_pred_norm': 'prediction_norm'}
    df = df.rename(columns={k: v for k, v in renames.items() if k in df.columns})
    df['_label'] = label
    return df

def apply_filters(df):
    if FILTER_L1 and 'l1' in df.columns:
        df = df[df['l1'] == FILTER_L1]
    if FILTER_SPEAKER and 'speaker' in df.columns:
        df = df[df['speaker'] == FILTER_SPEAKER]
    return df

def compare(da: pd.DataFrame, model_name: str) -> dict:
    """Join filtered baseline rows `da` against `model_name`'s eval CSV and
    precompute win/draw/loss stats, an L1 breakdown, and best/worst tables.

    Columns from the baseline get a `_baseline` suffix, columns from the
    comparison model get a `_bridge` suffix. `{metric}_delta` is always
    `bridge - baseline`: positive means the comparison model is worse than
    the baseline (higher WER), negative means it's better (lower WER).
    """
    db = apply_filters(load(resolve(model_name), model_name))

    metric_cols_a = [c for c in da.columns if c not in NON_METRIC]
    metric_cols_b = [c for c in db.columns if c not in NON_METRIC]
    shared_metrics = [c for c in metric_cols_a if c in metric_cols_b]
    cols_to_show = SHOW_COLS if SHOW_COLS else shared_metrics

    keep_a = ['utterance_id', 'speaker'] + (['l1'] if 'l1' in da.columns else []) + \
             ['text'] + cols_to_show + \
             (['prediction_norm'] if 'prediction_norm' in da.columns else [])
    keep_b = ['utterance_id', 'speaker'] + cols_to_show + \
             (['prediction_norm'] if 'prediction_norm' in db.columns else [])

    merged = da[keep_a].merge(
        db[[c for c in keep_b if c in db.columns]],
        on=['utterance_id', 'speaker'],
        suffixes=('_baseline', '_bridge'),
        how='inner'
    )

    for c in cols_to_show:
        c_base, c_bridge = f'{c}_baseline', f'{c}_bridge'
        if c_base in merged.columns and c_bridge in merged.columns:
            merged[f'{c}_delta'] = merged[c_bridge] - merged[c_base]

    pm_delta = f'{PRIMARY_METRIC}_delta'
    pm_bridge = f'{PRIMARY_METRIC}_bridge'
    is_win  = merged[pm_delta] < 0
    is_loss = merged[pm_delta] > 0
    is_draw = merged[pm_delta] == 0
    is_zero = merged[pm_bridge] == 0
    winloss_counts = {
        'wins':          int(is_win.sum()),
        'corrected':     int((is_win & is_zero).sum()),    # win that lands on 0 WER
        'improved':      int((is_win & ~is_zero).sum()),   # win that's still nonzero
        'draws':         int(is_draw.sum()),
        'draws_zero':    int((is_draw & is_zero).sum()),   # tied at 0 WER
        'draws_nonzero': int((is_draw & ~is_zero).sum()),  # tied but nonzero
        'losses':        int(is_loss.sum()),
    }

    l1_table = None
    if 'l1' in merged.columns:
        rows = []
        for l1, g in merged.groupby('l1'):
            row = {'l1': l1, 'n': len(g)}
            for c in cols_to_show:
                c_base, c_bridge = f'{c}_baseline', f'{c}_bridge'
                row[f'{c}_baseline'] = g[c_base].mean()
                row[f'{c}_bridge'] = g[c_bridge].mean()
                row[f'{c}_delta'] = g[c_bridge].mean() - g[c_base].mean()
            rows.append(row)
        l1_table = pd.DataFrame(rows).set_index('l1').round(4)

    text_cols   = ['utterance_id', 'speaker'] + (['l1'] if 'l1' in merged.columns else []) + ['text']
    pred_cols   = [c for c in merged.columns if 'prediction_norm' in c]
    metric_disp = [c for c in merged.columns if any(c.startswith(m) for m in cols_to_show)]
    browse_cols = text_cols + pred_cols + metric_disp

    best_wins    = merged.sort_values(pm_delta, ascending=True).head(TOP_N)[browse_cols].reset_index(drop=True)
    worst_losses = merged.sort_values(pm_delta, ascending=False).head(TOP_N)[browse_cols].reset_index(drop=True)

    return {
        'name': model_name,
        'merged': merged,
        'n': len(merged),
        'cols_to_show': cols_to_show,
        'winloss_counts': winloss_counts,
        'l1_table': l1_table,
        'best_wins': best_wins,
        'worst_losses': worst_losses,
    }

da_baseline = apply_filters(load(path_baseline, BASELINE))
print(f'Baseline {BASELINE!r}: {len(da_baseline)} rows')

results = [compare(da_baseline, name) for name in COMPARISON_MODELS]

print(f'\nComputed {len(results)} comparison(s) against baseline:')
for r in results:
    wl = r['winloss_counts']
    print(f"  {r['name']:35s} n={r['n']:5d}  wins={wl['wins']:4d} (corrected={wl['corrected']:4d}, improved={wl['improved']:4d})"
          f"  draws={wl['draws']:4d} (zero={wl['draws_zero']:4d}, nonzero={wl['draws_nonzero']:4d})  losses={wl['losses']:4d}")

Baseline 'baseline:whisper': 31395 rows

Computed 7 comparison(s) against baseline:
  bridge_dtw_eps_0.5                  n= 7796  wins= 635 (corrected= 180, improved= 455)  draws=5935 (zero=3156, nonzero=2779)  losses=1225
  bridge_dtw_eps_0.5_odesampling      n= 7796  wins= 200 (corrected=  45, improved= 155)  draws=7096 (zero=3396, nonzero=3700)  losses= 499
  bridge_position_eps_1.5             n= 7796  wins=  44 (corrected=   4, improved=  40)  draws= 118 (zero=  27, nonzero=  91)  losses=7633
  bridge_dtw_fixed_eps_0.5            n= 7796  wins= 981 (corrected= 312, improved= 669)  draws=5811 (zero=3195, nonzero=2616)  losses=1003
  bridge_dtw_fixed_eps_0.5_odesampling n= 7796  wins=   5 (corrected=   1, improved=   4)  draws=7780 (zero=3484, nonzero=4296)  losses=  10
  bridge_dtw_fixed_x0_0.5             n= 7796  wins= 982 (corrected= 328, improved= 654)  draws=5423 (zero=3106, nonzero=2317)  losses=1390
  bridge_dtw_fixed_x0_0.5_odesampling n= 7796  wins=1038 (corrected= 333, improved= 705)  draws=5667 (zero=3195, nonzero=2472)  losses=1090

In [25]:
from IPython.display import display, Markdown

pm = PRIMARY_METRIC
raw_rows, pct_rows = [], []
for r in results:
    merged, wl, n = r['merged'], r['winloss_counts'], r['n']
    baseline_mean = merged[f'{pm}_baseline'].mean()
    bridge_mean   = merged[f'{pm}_bridge'].mean()

    raw_rows.append({
        'model': r['name'],
        'n': n,
        f'{pm}_baseline': baseline_mean,
        f'{pm}_bridge': bridge_mean,
        f'{pm}_delta': bridge_mean - baseline_mean,
        'wins': wl['wins'],
        'corrected': wl['corrected'],
        'improved': wl['improved'],
        'draws': wl['draws'],
        'draws_zero': wl['draws_zero'],
        'draws_nonzero': wl['draws_nonzero'],
        'losses': wl['losses'],
    })
    pct_rows.append({
        'model': r['name'],
        'win_%':           wl['wins']          / n * 100,
        'corrected_%':     wl['corrected']     / n * 100,
        'improved_%':      wl['improved']      / n * 100,
        'draw_%':          wl['draws']         / n * 100,
        'draws_zero_%':    wl['draws_zero']    / n * 100,
        'draws_nonzero_%': wl['draws_nonzero'] / n * 100,
        'loss_%':          wl['losses']        / n * 100,
    })

overview_raw = pd.DataFrame(raw_rows).set_index('model').round(4)
overview_pct = pd.DataFrame(pct_rows).set_index('model').round(4)

display(Markdown('**Raw counts (wins split into corrected [→0 WER] / improved [still nonzero]; '
                 'draws split into zero / nonzero):**'))
display(overview_raw)
display(Markdown('**Percentages (of compared utterances `n`):**'))
display(overview_pct)

**Raw counts (wins split into corrected [→0 WER] / improved [still nonzero]; draws split into zero / nonzero):**

,n,utt_wer_baseline,utt_wer_bridge,utt_wer_delta,wins,corrected,improved,draws,draws_zero,draws_nonzero,losses
model,,,,,,,,,,,
bridge_dtw_eps_0.5,7796,0.154,0.1915,0.0374,635,180,455,5935,3156,2779,1225
bridge_dtw_eps_0.5_odesampling,7796,0.154,0.2285,0.0745,200,45,155,7096,3396,3700,499
bridge_position_eps_1.5,7796,0.154,6.7746,6.6206,44,4,40,118,27,91,7633
bridge_dtw_fixed_eps_0.5,7796,0.154,0.1941,0.0400,981,312,669,5811,3195,2616,1003
bridge_dtw_fixed_eps_0.5_odesampling,7796,0.154,0.1541,0.0001,5,1,4,7780,3484,4296,10
bridge_dtw_fixed_x0_0.5,7796,0.154,0.4194,0.2653,982,328,654,5423,3106,2317,1390
bridge_dtw_fixed_x0_0.5_odesampling,7796,0.154,0.3005,0.1465,1038,333,705,5667,3195,2472,1090

**Percentages (of compared utterances `n`):**

,win_%,corrected_%,improved_%,draw_%,draws_zero_%,draws_nonzero_%,loss_%
model,,,,,,,
bridge_dtw_eps_0.5,8.1452,2.3089,5.8363,76.1288,40.4823,35.6465,15.7132
bridge_dtw_eps_0.5_odesampling,2.5654,0.5772,1.9882,91.0210,43.5608,47.4602,6.4007
bridge_position_eps_1.5,0.5644,0.0513,0.5131,1.5136,0.3463,1.1673,97.9092
bridge_dtw_fixed_eps_0.5,12.5834,4.0021,8.5813,74.5382,40.9826,33.5557,12.8656
bridge_dtw_fixed_eps_0.5_odesampling,0.0641,0.0128,0.0513,99.7948,44.6896,55.1052,0.1283
bridge_dtw_fixed_x0_0.5,12.5962,4.2073,8.3889,69.5613,39.8409,29.7204,17.8297
bridge_dtw_fixed_x0_0.5_odesampling,13.3145,4.2714,9.0431,72.6911,40.9826,31.7086,13.9815

In [26]:
from IPython.display import display, Markdown

pd.set_option('display.max_colwidth', 80)
pd.set_option('display.max_rows', 200)

for r in results:
    display(Markdown(f"## {r['name']}"))

    wl, n = r['winloss_counts'], r['n']
    print(f"Utterances compared: {n}")
    print(f"  wins   (model better than baseline): {wl['wins']:5d}  ({wl['wins']/n*100:5.2f}%)")
    print(f"  draws  (tied):                       {wl['draws']:5d}  ({wl['draws']/n*100:5.2f}%)")
    print(f"  losses (model worse than baseline):  {wl['losses']:5d}  ({wl['losses']/n*100:5.2f}%)")

    if r['l1_table'] is not None:
        display(Markdown("**By L1:**"))
        display(r['l1_table'])

    display(Markdown(f"**Best wins — top {TOP_N} by `{PRIMARY_METRIC}` delta (model beats baseline most):**"))
    display(r['best_wins'])

    display(Markdown(f"**Worst losses — top {TOP_N} by `{PRIMARY_METRIC}` delta (model loses to baseline most):**"))
    display(r['worst_losses'])

## bridge_dtw_eps_0.5

Utterances compared: 7796
  wins   (model better than baseline):   635  ( 8.15%)
  draws  (tied):                        5935  (76.13%)
  losses (model worse than baseline):   1225  (15.71%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          0.1399         0.0091
Chinese     1130            0.2010          0.2965         0.0955
English     1132            0.0402          0.0448         0.0046
Hindi       1132            0.0708          0.0738         0.0030
Korean      1131            0.0855          0.0902         0.0047
Spanish     1007            0.2364          0.2838         0.0474
Vietnamese  1132            0.3223          0.4214         0.0991

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0155,HQTV,Vietnamese,Won't you draw up gentlemen,one youve rarred and the other youve chandlemen,wont you grow up in chandlerman,1.600000,0.600000,-1.000000
1,arctic_a0381,SVBI,Hindi,My name's Ferguson,my name is fargusson,my names ferguson,1.000000,0.000000,-1.000000
2,arctic_b0319,HQTV,Vietnamese,Daylight was tired profoundly tired,they lied to a tire a foully tire,they lied were tired profoundly tired,1.600000,0.600000,-1.000000
3,arctic_b0425,BDL,English,"There were orange-green, gold-green, and a copper-green.",there were orange green gold green and a copper green,there were orangegreen goldgreen and a coppergreen,0.857143,0.000000,-0.857143
4,arctic_a0480,EBVS,Spanish,Tom Spink has a harpoon,dont speak her phone,dont spink has a harpoon,1.000000,0.200000,-0.800000
5,arctic_b0207,ZHAA,Arabic,I'm as good as a man she urged,amasgut ezaman she urged,im as good as a man she urged,0.750000,0.000000,-0.750000
6,arctic_a0381,HJK,Korean,My name's Ferguson,my name is ferguson,my names ferguson,0.666667,0.000000,-0.666667
7,arctic_b0166,ZHAA,Arabic,Fast but endure,fast buttontoer,fast but endure,0.666667,0.000000,-0.666667
8,arctic_b0218,EBVS,Spanish,The issue was not in doubt,the issue was not in the up to date,the issue was not in doubt,0.666667,0.000000,-0.666667
9,arctic_b0079,HQTV,Vietnamese,The truth of it set Jeanne quivering,detroit stop is said to be a river ring,the choice of east said kenny weavering,1.285714,0.714286,-0.571429
10,arctic_b0173,SVBI,Hindi,To these he gave castor oil,to this he gave castroil,to these he gave castor oil,0.500000,0.000000,-0.500000
11,arctic_a0150,BWC,Chinese,Goodbye Pierre he shouted,goodbye pr he shot it,goodbye pia he shouted,0.750000,0.250000,-0.500000
12,arctic_a0440,BWC,Chinese,Yes sir I corrected,yes sir i correct it,yes sir i corrected,0.500000,0.000000,-0.500000
13,arctic_a0440,HQTV,Vietnamese,Yes sir I corrected,yes sir i correct it,yes sir i corrected,0.500000,0.000000,-0.500000
14,arctic_b0376,EBVS,Spanish,Thought I and a worthy fool he proved,so i am awarded for his proofs,i am a worthy for he proved,0.875000,0.375000,-0.500000
15,arctic_a0016,BWC,Chinese,There's Fort Churchill a rifle shot beyond the ridge asleep,there is a fourth chieftain a riff shot beyond the reach as a leap,theres ford chechel a rave shot beyond the reach,1.000000,0.500000,-0.500000
16,arctic_b0299,HQTV,Vietnamese,Miss Brodie's smile was slightly sarcastic,misbroadies my words like this sarcastic,misbroadys smile was slightly sarcastic,0.833333,0.333333,-0.500000
17,arctic_b0328,BWC,Chinese,Change chairs Daylight commanded,change chairs they like command it,change chairs stay like commanded,1.000000,0.500000,-0.500000
18,arctic_a0325,BDL,English,Whiz-zip-bang. Lop-Ear screamed with sudden anguish.,whiz zip bang lop ear screamed with sudden anguish,whizdip bang lopear screamed with sudden anguish,0.833333,0.333333,-0.500000
19,arctic_b0436,HQTV,Vietnamese,Famine had been my great ally,famed has been migrated alive,femmeit has been my great ally,0.833333,0.333333,-0.500000

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0404,HQTV,Vietnamese,Perrault found one with head buried in the grub box,perot found one his head buried in the club box,perots found one his head buried and in the the the the the the the the the ...,0.300000,43.500000,43.200000
1,arctic_b0172,BWC,Chinese,On the far corner of the compound fence a hawk brooded,on the far corner of the compound fence a hog brooded,on the far corner of the compound fence a hog hog hog hog hog hog hog hog ho...,0.090909,39.454545,39.363636
2,arctic_a0475,HQTV,Vietnamese,His outstretched arm dropped to his side and he paused,is our stretch arm brought to his side and he pose,its our stretch im brought to his side and hes brought to his side and hes b...,0.500000,37.400000,36.900000
3,arctic_a0327,BWC,Chinese,They were less stooped than we less springy in their movements,they were less stupid than me less springy in their movements,they were less stupid than me less stupid than me less stupid than me less s...,0.181818,31.909091,31.727273
4,arctic_a0366,EBVS,Spanish,A wildly exciting time was his during the week preceding Thursday the eighte...,a widely exciting time was his during the week preceding thursday the 18th,a widely exciting time was he during the week preceding thursday thursday th...,0.153846,16.692308,16.538462
5,arctic_b0309,HQTV,Vietnamese,Nor was Elam Harnish an exception,now was allahs harnessed an exception,now we are in the midst of the great greatest,0.500000,1.666667,1.166667
6,arctic_b0223,BWC,Chinese,They likewise are disinclined to being eaten,they likewise are disinclined to brain agent,likewise this is the same thing to bring to the system,0.285714,1.428571,1.142857
7,arctic_a0015,EBVS,Spanish,It's the aurora borealis,it is the aurora borealis,it is their role of realist,0.500000,1.500000,1.000000
8,arctic_b0311,BDL,English,The 29th very foggy.,the 29th very foggy,29,0.000000,1.000000,1.000000
9,arctic_a0017,EBVS,Spanish,From that moment his friendship for Belize turns to hatred and jealousy,from that moment his friendship for belize turns to hatred and jealousy,from that moment his friendship for bellis is in the hands of the people of ...,0.000000,1.000000,1.000000
10,arctic_b0119,SVBI,Hindi,Billinger may arrive in time,billinger may arrive in time,billingham arayana,0.000000,1.000000,1.000000
11,arctic_a0208,EBVS,Spanish,Youth had come back to her freed from the yoke of oppression,youth has come back to her freed from the yoke of oppression,you,0.083333,1.000000,0.916667
12,arctic_a0292,EBVS,Spanish,Here in the midmorning the first casualty occurred,here in the midmorning the first catchall occurred,here in the mid morning the first catcher is a little bit more,0.125000,1.000000,0.875000
13,arctic_a0407,HQTV,Vietnamese,Mercedes screamed cried laughed and manifested the chaotic abandonment of hy...,mercedes screamed cried laughed and manifested the chaotic abundance of hyst...,masadas scream cry laugh and manifest it the child take,0.090909,0.909091,0.818182
14,arctic_b0014,SVBI,Hindi,Whitefish Gregson whitefish and trout,whitefish gryxon whitefish and trout,white fish gryxon white fish and trout,0.200000,1.000000,0.800000
15,arctic_b0119,HQTV,Vietnamese,Billinger may arrive in time,billinger may arrive in time,billinger made a right turn,0.000000,0.800000,0.800000
16,arctic_b0014,EBVS,Spanish,Whitefish Gregson whitefish and trout,whitefish grayton whitefish and draught,white fish written white fish and drought,0.400000,1.200000,0.800000
17,arctic_a0560,EBVS,Spanish,His mouth opened words shaped vainly on his lips,his mouth opened wore shaped vainly on his lips,his mouths open,0.111111,0.888889,0.777778
18,arctic_b0449,HQTV,Vietnamese,Also she wouldn't walk,also she wouldnt walk,also she would the world,0.000000,0.750000,0.750000
19,arctic_b0220,BWC,Chinese,Harry Bancroft Dave lied,harry bancroft dave lydde,harrybankcraftcom,0.250000,1.000000,0.750000

## bridge_dtw_eps_0.5_odesampling

Utterances compared: 7796
  wins   (model better than baseline):   200  ( 2.57%)
  draws  (tied):                        7096  (91.02%)
  losses (model worse than baseline):    499  ( 6.40%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          0.1295        -0.0013
Chinese     1130            0.2010          0.3902         0.1892
English     1132            0.0402          0.0429         0.0027
Hindi       1132            0.0708          0.0712         0.0004
Korean      1131            0.0855          0.0875         0.0020
Spanish     1007            0.2364          0.4279         0.1915
Vietnamese  1132            0.3223          0.4724         0.1501

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_b0257,HQTV,Vietnamese,Tudor surveyed him with withering disgust,to the survey he was with three discussed,to the surveying with withering disgust,1.166667,0.500000,-0.666667
1,arctic_b0166,ZHAA,Arabic,Fast but endure,fast buttontoer,fast but endure,0.666667,0.000000,-0.666667
2,arctic_b0043,HQTV,Vietnamese,It won't be for sale,its one beast for self,it wont be for self,0.800000,0.200000,-0.600000
3,arctic_a0448,ZHAA,Arabic,I was Hump cabin boy on the schooner Ghost,i was humped kept in boy and this cooner ghost,i was hump cabin boy and the schooner ghost,0.666667,0.111111,-0.555556
4,arctic_a0440,HQTV,Vietnamese,Yes sir I corrected,yes sir i correct it,yes sir i corrected,0.500000,0.000000,-0.500000
5,arctic_a0083,HQTV,Vietnamese,A shadow was creeping over Pierre's eyes,a shadow will creep in over a pair of eyes,a shadow will creeping over a pure eyes,0.857143,0.428571,-0.428571
6,arctic_a0482,HQTV,Vietnamese,And their chief virtue lies in that they will never wear out,and the chef will be too lie and start to be neverware,and the chef will to lie in that they will never wear,0.916667,0.500000,-0.416667
7,arctic_a0195,HQTV,Vietnamese,But a strange thing happened,but the strength thing happened,but a strange thing happened,0.400000,0.000000,-0.400000
8,arctic_a0192,HJK,Korean,He did not rush in,he did not russian,he did not rush in,0.400000,0.000000,-0.400000
9,arctic_b0311,BWC,Chinese,The twenty ninth very foggy,the 29th verifoggy,the 29th very foggy,0.800000,0.400000,-0.400000
10,arctic_a0309,BWC,Chinese,White Leghorns said Missus Mortimer,whites lower organs assess mrs mortimer,white logon says mrs mortimer,1.000000,0.600000,-0.400000
11,arctic_b0325,EBVS,Spanish,It was a gigantic inadequacy,it was a gigantic in a ducasi,it was a gigantic inaducosy,0.600000,0.200000,-0.400000
12,arctic_a0492,HQTV,Vietnamese,Burnt out like the crater of a volcano,burn out light greater of the volcano,burn out like the crater of the volcano,0.625000,0.250000,-0.375000
13,arctic_a0359,BWC,Chinese,Earth and gravel seemed to fill the pan,earth and gryvel seemed to feel the pain,earth and gravel seemed to fill the pan,0.375000,0.000000,-0.375000
14,arctic_a0543,HQTV,Vietnamese,I had been born with no organic chemical predisposition toward alcohol,i have been born with no organic chemistry school with this devotion to our ...,i have been born with no organic chemistry school great distribution toward ...,0.818182,0.454545,-0.363636
15,arctic_a0498,BWC,Chinese,The lines were now very taut,the line was now very tall,the lines were now very tall,0.500000,0.166667,-0.333333
16,arctic_b0019,ZHAA,Arabic,His slim hands gripped the edges of the table,heres a slim hand script the edges of the table,his slim hands grip the edges of the table,0.444444,0.111111,-0.333333
17,arctic_a0452,SVBI,Hindi,Three oilers and a fourth engineer was his greeting,three oilers and a fourth engineer versus greetings,three oilers and a fourth engineer was his greeting,0.333333,0.000000,-0.333333
18,arctic_a0028,HJK,Korean,Robbery bribery fraud,robbery bribery fru out,robbery bribery fruiting,0.666667,0.333333,-0.333333
19,arctic_b0472,BWC,Chinese,Ernest saw in the affair the most sinister import,earn it all in the fair the most sinister import,ernest saw in the fair the most sinister import,0.444444,0.111111,-0.333333

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0404,HQTV,Vietnamese,Perrault found one with head buried in the grub box,perot found one his head buried in the club box,perots foul one his head buried in the in the in the in the in the in the in...,0.300000,43.700000,43.400000
1,arctic_a0434,BWC,Chinese,A half a case of tobacco was worth three pounds,i have a case of tobacco worth 3 pounds,i have a case of tobacco was worth worth worth worth worth worth worth worth...,0.400000,43.800000,43.400000
2,arctic_a0491,EBVS,Spanish,And as in denial of guilt the one legged boy replied,and as in the nile of guild the one let boy reply it,and as in the nile of guild the one who is the one who is the one who is the...,0.545455,39.727273,39.181818
3,arctic_a0503,BWC,Chinese,His beady black eyes saw bargains where other men saw bankruptcy,he beat the black eye saw blank knees where other men saw bankruptcy,he beaded black eyes saw blank knees where other men saw blank knees where o...,0.545455,39.636364,39.090909
4,arctic_b0075,EBVS,Spanish,In that case he could not miss them if he used caution,in that case he could not miss them if he used cauchon,in that case he could not miss them if he could not miss them if he could no...,0.083333,36.083333,36.000000
5,arctic_a0246,BWC,Chinese,He had heard always how he was the lover of the Princess Naomi,he had heard always how he was the lover of the princess naomi,he had heard always how he was the lover of the the lover of the lover of th...,0.000000,33.307692,33.307692
6,arctic_a0022,HQTV,Vietnamese,Hardly were our plans made public before we were met by powerful opposition,hardly were our plans made public before we were met by powerful opposition,hardly were our plans made public before we were met by by by by by by by by...,0.000000,33.230769,33.230769
7,arctic_a0422,EBVS,Spanish,Halfway around the track one donkey got into an argument with its rider,the highway around the track or one donkey go into an argument with its rider,the highway around the track or one donkey go into an argument with its its ...,0.307692,33.384615,33.076923
8,arctic_b0204,HQTV,Vietnamese,Down through the perfume weighted air fluttered the snowy fluffs of the cott...,dialed through the perfume weighted air flutter the snowy fluff on the cotto...,dial through the perfume weighted air flutter the snowy fluff on the fluffy ...,0.461538,33.230769,32.769231
9,arctic_a0047,BWC,Chinese,Close beside him gleamed the white fangs of the wolf dog,clothes beside him gleamed the white thong of the wolf dog,clothes beside him gleamed the white thong of the white thong of the white t...,0.181818,31.636364,31.454545
10,arctic_a0157,HQTV,Vietnamese,He had worshiped her as Dante might have worshiped Beatrice,he had worshipped her as dental mine would have worshipped her tray,he had worshipped her at dental mine would have worshipped her at dental min...,0.700000,30.700000,30.000000
11,arctic_a0503,EBVS,Spanish,His beady black eyes saw bargains where other men saw bankruptcy,his pretty black eyes saw bargains were other men saw burgundy,his beauty black eyes so bargains were other mens so bargains were other men...,0.272727,28.363636,28.090909
12,arctic_b0323,HQTV,Vietnamese,Crickets began to chirp and more geese and ducks flew overhead,tricked began to chirp and mogies and duck flew overhead,tricked began to chirp and mogeez and chirp and mogeez and chirp and mogeez ...,0.363636,23.181818,22.818182
13,arctic_b0407,EBVS,Spanish,Of course much grumbling went on and little outbursts were continually occur...,of course much crumbling went on and little of births were continually occur...,of course much crumbling went on and little of births were of course much cr...,0.250000,22.916667,22.666667
14,arctic_a0291,BWC,Chinese,The weeks had gone by and no overt acts had been attempted,the weeks had gone by and no words had been attempted,the weeks have gone by and no words act act act act act act act act act act ...,0.166667,18.333333,18.166667
15,arctic_a0026,BWC,Chinese,It occurred to me that there would have to be an accounting,it occurred to me that there would have to be an accounting,it occurred to me that there would have to be an a a a a a a a a a a a a a a...,0.000000,18.000000,18.000000
16,arctic_a0366,EBVS,Spanish,A wildly exciting time was his during the week preceding Thursday the eighte...,a widely exciting time was his during the week preceding thursday the 18th,a widely exciting time was his during the week preceding thursday thursday t...,0.153846,16.615385,16.461538
17,arctic_a0430,BWC,Chinese,Nevertheless we found ourselves once more in the high seat of abundance,nevertheless we found ourselves once more in the high seat of abundance,nevertheless we found ourselves once more in the high seat ofthehigh seat of...,0.000000,9.083333,9.083333
18,arctic_a0484,BDL,English,No-sir-ee.,no surrey,no sir re,2.000000,3.000000,1.000000
19,arctic_b0484,HQTV,Vietnamese,This the Iron Heel foresaw and laid its schemes accordingly,this is the iron hill for sore and lake ischemic colony,this is the iron hill for sore and legged ischemic this is the iron hill for...,0.800000,1.600000,0.800000

## bridge_position_eps_1.5

Utterances compared: 7796
  wins   (model better than baseline):    44  ( 0.56%)
  draws  (tied):                         118  ( 1.51%)
  losses (model worse than baseline):   7633  (97.91%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          7.2002         7.0693
Chinese     1130            0.2010          6.8750         6.6740
English     1132            0.0402          6.4965         6.4563
Hindi       1132            0.0708          6.3520         6.2812
Korean      1131            0.0855          6.9889         6.9034
Spanish     1007            0.2364          7.4013         7.1649
Vietnamese  1132            0.3223          6.1778         5.8555

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0155,HQTV,Vietnamese,Won't you draw up gentlemen,one youve rarred and the other youve chandlemen,warrnoura anandam,1.600000,1.000000,-0.600000
1,arctic_b0257,EBVS,Spanish,Tudor surveyed him with withering disgust,the two of us will bite him with great disgust,to serve him with the,1.166667,0.666667,-0.500000
2,arctic_b0425,BDL,English,"There were orange-green, gold-green, and a copper-green.",there were orange green gold green and a copper green,there are orangegreen and greengreen and a coppergreen,0.857143,0.428571,-0.428571
3,arctic_a0060,ZHAA,Arabic,Anyway no one saw her like that,anyway no ones so hair like that,anyway no one saw her like that,0.428571,0.000000,-0.428571
4,arctic_a0287,HQTV,Vietnamese,Keep an eye on him,keep a nigh on him,keep an eye on him,0.400000,0.000000,-0.400000
5,arctic_a0484,HJK,Korean,No sir ee,no sorry,no sir,0.666667,0.333333,-0.333333
6,arctic_b0369,HQTV,Vietnamese,You see we were teaching ourselves,you see we were teaching our service,you see we were teaching ourselves,0.333333,0.000000,-0.333333
7,arctic_a0310,HQTV,Vietnamese,Massage under tension was the cryptic reply,much of the charges and the tensions were a critical reply,much more,1.285714,1.000000,-0.285714
8,arctic_a0590,HQTV,Vietnamese,In a way he is my protege,in a way shes my protector,in a way he is my own,0.428571,0.142857,-0.285714
9,arctic_b0338,HQTV,Vietnamese,It was unobtrusive yet it was there,is there enough truth to see yes its there,he was a very good man,1.142857,0.857143,-0.285714
10,arctic_b0211,EBVS,Spanish,This is eighteen eighty,it is 1880,this is 18,0.750000,0.500000,-0.250000
11,arctic_b0019,EBVS,Spanish,His slim hands gripped the edges of the table,this is lim hans repeat date of the day world,hes llemiheurs rewerent of the people of the world,0.888889,0.666667,-0.222222
12,arctic_b0529,HQTV,Vietnamese,Come on Del Mar challenged,come on they are my challenge,come on youre a hero,0.800000,0.600000,-0.200000
13,arctic_b0327,EBVS,Spanish,He had been so easy,he got been so easy,he had been so easy,0.200000,0.000000,-0.200000
14,arctic_b0014,HQTV,Vietnamese,Whitefish Gregson whitefish and trout,why fish crescent why fish and truth,ill fix it,1.200000,1.000000,-0.200000
15,arctic_a0346,EBVS,Spanish,Get down and dig in,good town auntie king,and the world,1.000000,0.800000,-0.200000
16,arctic_a0309,HJK,Korean,White Leghorns said Missus Mortimer,white legrines that misses more to more,whiteeyeedeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeyeeye...,1.200000,1.000000,-0.200000
17,arctic_b0285,BWC,Chinese,The hyena proceeded to dine,high enough to proceed to dying,the hyenaeura is a hyenaeura,1.000000,0.800000,-0.200000
18,arctic_b0325,HQTV,Vietnamese,It was a gigantic inadequacy,its got a gigantic and other crazy,he was a very good man,1.000000,0.800000,-0.200000
19,arctic_a0016,BWC,Chinese,There's Fort Churchill a rifle shot beyond the ridge asleep,there is a fourth chieftain a riff shot beyond the reach as a leap,theres a little bit of a difference,1.000000,0.800000,-0.200000

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_b0178,ZHAA,Arabic,Also I want information,also i want information,all all all all all all all all all all all all all all all all all all all ...,0.00,111.00,111.00
1,arctic_b0311,BDL,English,The 29th very foggy.,the 29th very foggy,the the the the the the the the the the the the the the the the the the the ...,0.00,110.75,110.75
2,arctic_a0150,BDL,English,"Goodbye, Pierre, he shouted.",goodbye pierre he shouted,goodbye he he he he he he he he he he he he he he he he he he he he he he he...,0.00,110.25,110.25
3,arctic_a0150,SVBI,Hindi,Goodbye Pierre he shouted,goodbye pierre he shouted,goodbye he he he he he he he he he he he he he he he he he he he he he he he...,0.00,110.25,110.25
4,arctic_a0329,BWC,Chinese,Ah indeed,aha indeed,ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah a...,0.50,110.50,110.00
5,arctic_a0329,ZHAA,Arabic,Ah indeed,indeed,ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah ah a...,0.50,110.50,110.00
6,arctic_a0150,BWC,Chinese,Goodbye Pierre he shouted,goodbye pr he shot it,buiyi he he he he he he he he he he he he he he he he he he he he he he he h...,0.75,110.25,109.50
7,arctic_a0150,HJK,Korean,Goodbye Pierre he shouted,goodbye pierre he shouted,goodbye he heared he heared he heared he he he he he he he he he he he he he...,0.00,108.75,108.75
8,arctic_b0375,ZHAA,Arabic,Man could not conquer them,man could not conquer them,manhood to to to to to to to to to to to to to to to to to to to to to to to...,0.00,88.60,88.60
9,arctic_a0311,HJK,Korean,Therefore hurrah for the game,therefore hooray for the game,there are a very rare and rare rare rare rare rare rare rare rare rare rare ...,0.20,88.80,88.60
10,arctic_b0088,BWC,Chinese,Until I die he exclaimed,until i die he exclaimed,and to i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i...,0.00,88.60,88.60
11,arctic_b0351,BDL,English,"Matthewson, who's this bookkeeper, Rogers.",matheson whos this bookkeeper rogers,is the book of the book of the book of the book of the book of the book of t...,0.20,88.80,88.60
12,arctic_b0205,HQTV,Vietnamese,You were destroying my life,you were destroying my life,you are the one who is going to be the one to be the one to be the one to be...,0.00,88.60,88.60
13,arctic_a0489,SVBI,Hindi,They were artists not biologists,they were artists not biologists,they are our our our our our our our our our our our our our our our our our...,0.00,88.60,88.60
14,arctic_a0243,BWC,Chinese,I only read the quotations,i only read the quotations,i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i ...,0.00,88.60,88.60
15,arctic_b0088,EBVS,Spanish,Until I die he exclaimed,until i die he exclaimed,and i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i ...,0.00,88.60,88.60
16,arctic_a0351,SVBI,Hindi,It was more like sugar,it was more like sugar,its a little bit like a little bit of a little bit of a little bit of a litt...,0.00,88.40,88.40
17,arctic_b0088,BDL,English,"Until I die, he exclaimed.",until i die he exclaimed,until i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i ...,0.00,88.40,88.40
18,arctic_a0489,EBVS,Spanish,They were artists not biologists,they were artists not biologists,they were our our our our our our our our our our our our our our our our ou...,0.00,88.40,88.40
19,arctic_b0286,ZHAA,Arabic,The time was considered auspicious,the time was considered auspicious,the time is set to be set to be set to be set to be set to be set to be set ...,0.00,88.40,88.40

## bridge_dtw_fixed_eps_0.5

Utterances compared: 7796
  wins   (model better than baseline):   981  (12.58%)
  draws  (tied):                        5811  (74.54%)
  losses (model worse than baseline):   1003  (12.87%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          0.2010         0.0702
Chinese     1130            0.2010          0.2392         0.0381
English     1132            0.0402          0.0403         0.0000
Hindi       1132            0.0708          0.0670        -0.0038
Korean      1131            0.0855          0.0846        -0.0009
Spanish     1007            0.2364          0.2377         0.0013
Vietnamese  1132            0.3223          0.4934         0.1711

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0381,SVBI,Hindi,My name's Ferguson,my name is fargusson,my names ferguson,1.000000,0.000000,-1.000000
1,arctic_b0425,BDL,English,"There were orange-green, gold-green, and a copper-green.",there were orange green gold green and a copper green,there were orangegreen goldgreen and a coppergreen,0.857143,0.000000,-0.857143
2,arctic_a0589,BWC,Chinese,I was sick once typhoid,i will seek once time for it,i was sick once typhoek,1.000000,0.200000,-0.800000
3,arctic_b0354,HQTV,Vietnamese,It's that much junk,is that mcchunk,its that much junk,0.750000,0.000000,-0.750000
4,arctic_b0207,ZHAA,Arabic,I'm as good as a man she urged,amasgut ezaman she urged,im as good as a man she urged,0.750000,0.000000,-0.750000
5,arctic_a0119,HQTV,Vietnamese,Jeanne was turning the bow shoreward,genie would turn in the bull straw world,ginny was turning the ball strong,1.166667,0.500000,-0.666667
6,arctic_a0389,BWC,Chinese,Mab she said,mab shes sad,mab she said,0.666667,0.000000,-0.666667
7,arctic_b0166,ZHAA,Arabic,Fast but endure,fast buttontoer,fast but endure,0.666667,0.000000,-0.666667
8,arctic_b0218,EBVS,Spanish,The issue was not in doubt,the issue was not in the up to date,the issue was not in doubt,0.666667,0.000000,-0.666667
9,arctic_a0381,HJK,Korean,My name's Ferguson,my name is ferguson,my names ferguson,0.666667,0.000000,-0.666667
10,arctic_b0319,HQTV,Vietnamese,Daylight was tired profoundly tired,they lied to a tire a foully tire,they lied were tired were fowlly tired,1.600000,1.000000,-0.600000
11,arctic_a0155,HQTV,Vietnamese,Won't you draw up gentlemen,one youve rarred and the other youve chandlemen,one youve rarred in chandlerman,1.600000,1.000000,-0.600000
12,arctic_a0589,HJK,Korean,I was sick once typhoid,i was sick once time for it,i was sick once typhoid,0.600000,0.000000,-0.600000
13,arctic_b0079,HQTV,Vietnamese,The truth of it set Jeanne quivering,detroit stop is said to be a river ring,the choice of is said kenny weavering,1.285714,0.714286,-0.571429
14,arctic_a0440,HQTV,Vietnamese,Yes sir I corrected,yes sir i correct it,yes sir i corrected,0.500000,0.000000,-0.500000
15,arctic_a0329,EBVS,Spanish,Ah indeed,are indeed,ah indeed,0.500000,0.000000,-0.500000
16,arctic_a0396,EBVS,Spanish,A rising tide of fat had submerged them,a racing title had so much time,a rising tide of hot hot summers them,0.875000,0.375000,-0.500000
17,arctic_a0447,EBVS,Spanish,Ah it's growing dark and darker,is growing darker and darker,ah its growing dark and darker,0.500000,0.000000,-0.500000
18,arctic_a0330,EBVS,Spanish,Red Eye never committed a more outrageous deed,red eye and i recommended a more outrageous did,red eye never committed a more outrageous deed,0.500000,0.000000,-0.500000
19,arctic_a0329,BWC,Chinese,Ah indeed,aha indeed,ah indeed,0.500000,0.000000,-0.500000

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0015,HQTV,Vietnamese,It's the aurora borealis,is it already boring,hes an old old old old old old old old old old old old old old old old old o...,1.000000,55.750000,54.750000
1,arctic_a0407,BWC,Chinese,Mercedes screamed cried laughed and manifested the chaotic abandonment of hy...,macedas cried laughed and manifested the chaos and abandonment of hysteria,mercedes climbed cried laughed and manifested the chaos of the chaos of the ...,0.363636,39.454545,39.090909
2,arctic_b0313,ZHAA,Arabic,The apron string loomed near and he shied like an unbroken colt,the upper and strength loomed near and he shied like an endbroken cult,the upper and the lower part of the body is the upper and the lower part of ...,0.416667,36.833333,36.416667
3,arctic_b0385,HQTV,Vietnamese,Last night he showed all the symptoms of coming down with pneumonia,last night he showed on the scene some of coming down with yunonia,last night he showed on the scene of coming to the scene of coming to the sc...,0.333333,36.416667,36.083333
4,arctic_a0482,ZHAA,Arabic,And their chief virtue lies in that they will never wear out,and their teeth fertilize in that they will then be wears out,and their chiefs were two lies in that they were they were they were they we...,0.500000,36.416667,35.916667
5,arctic_a0543,HQTV,Vietnamese,I had been born with no organic chemical predisposition toward alcohol,i have been born with no organic chemistry school with this devotion to our ...,i have been born with no organic chemistry nor am i born with no organic che...,0.818182,35.363636,34.545455
6,arctic_b0172,HQTV,Vietnamese,On the far corner of the compound fence a hawk brooded,on the far corner of the compile fans or hope wrote it,on the far corner of the campofans on the far corner of the campofans on the...,0.545455,27.818182,27.272727
7,arctic_a0250,HQTV,Vietnamese,He had observed the business life of Hawaii and developed a vaulting ambition,he has observed the business life of hawaii and the value of vowing ambition,he has observed the business life of hawaii and developed a vial of vial of ...,0.384615,22.230769,21.846154
8,arctic_a0149,ZHAA,Arabic,For an instant he saw Pierre drawn like a silhouette against the sky,for an instant he saw pier trone like a silhouette against the sky,for an instant he saw pierre throwing like a silverlike silverlike silverlik...,0.153846,11.230769,11.076923
9,arctic_a0325,BWC,Chinese,Whiz zip bang Lop Ear screamed with sudden anguish,with deep bound lop air screamed with sudden anguish,with steep long lowpitched lowpitched lowpitched lowpitched lowpitched lowpi...,0.444444,10.111111,9.666667
10,arctic_a0276,HQTV,Vietnamese,Oolong Atoll was one hundred and forty miles in circumference,olong atoll was 140 miles in circumference,olong olong olong olong olong olong olong olong olong olong olong olong olon...,0.500000,8.900000,8.400000
11,arctic_a0050,BWC,Chinese,In spite of their absurdity the words affected Philip curiously,in spirit of their assertedity the words affect philip curiously,its been a while since ive seen a video of a person who is a little bit more...,0.300000,2.400000,2.100000
12,arctic_b0328,HJK,Korean,Change chairs Daylight commanded,change chairs daylight commanded,change chair stay light command it,0.000000,1.250000,1.250000
13,arctic_a0263,HQTV,Vietnamese,Joan looked triumphantly at Sheldon who bowed,charm looked triumphantly as sheldon who bowed,charne looked triumphantly as she looked as if she was a child,0.285714,1.428571,1.142857
14,arctic_a0086,HJK,Korean,Death had come with terrible suddenness,death had come with terrible suddenness,thats it,0.000000,1.000000,1.000000
15,arctic_a0235,BWC,Chinese,His voice was passionately rebellious,his wife was passionately rebalanced,his wife was passionate till he was rebuyless,0.400000,1.200000,0.800000
16,arctic_a0399,HQTV,Vietnamese,And here's another idea,and here another idea,and here are now the idea,0.250000,1.000000,0.750000
17,arctic_a0314,HQTV,Vietnamese,Thus was momentum gained in the Younger World,us momentum gain in the younger world,thus the world will be filled with joy and joy,0.375000,1.125000,0.750000
18,arctic_b0300,HQTV,Vietnamese,Does the old boy often go off at half cock that way,does the own point of go off at half cock that way,theres no one else,0.250000,1.000000,0.750000
19,arctic_b0449,HQTV,Vietnamese,Also she wouldn't walk,also she wouldnt walk,also she would do well,0.000000,0.750000,0.750000

## bridge_dtw_fixed_eps_0.5_odesampling

Utterances compared: 7796
  wins   (model better than baseline):     5  ( 0.06%)
  draws  (tied):                        7780  (99.79%)
  losses (model worse than baseline):     10  ( 0.13%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          0.1308        -0.0001
Chinese     1130            0.2010          0.2010         0.0000
English     1132            0.0402          0.0404         0.0001
Hindi       1132            0.0708          0.0708        -0.0000
Korean      1131            0.0855          0.0855        -0.0000
Spanish     1007            0.2364          0.2369         0.0005
Vietnamese  1132            0.3223          0.3224         0.0001

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_b0020,EBVS,Spanish,He made no reply as he waited for Whittemore to continue,he made no reply as he waits for a week more to continue,he made no reply as he waits for whitmore to continue,0.363636,0.181818,-0.181818
1,arctic_b0432,ZHAA,Arabic,He is a candidate rising from the serf class to our class,hes a candidate rising from the serve class to our class,he is a candidate rising from the serve class to our class,0.250000,0.083333,-0.166667
2,arctic_b0005,SVBI,Hindi,His slim fingers closed like steel about Philip's,his slim fingers closed like steel about phillips,his slim fingers closed like steel about philips,0.125000,0.000000,-0.125000
3,arctic_a0448,HJK,Korean,I was Hump cabin boy on the schooner Ghost,i was humped cabin boy on the shunar ghost,i was humped cabin boy on the schooner ghost,0.222222,0.111111,-0.111111
4,arctic_a0430,HQTV,Vietnamese,Nevertheless we found ourselves once more in the high seat of abundance,nevertheless we found our service one more in the high seas of abundant,nevertheless we found our service one more in the high seas of abundance,0.416667,0.333333,-0.083333
5,arctic_b0222,SVBI,Hindi,He was the leader and Tudor was his lieutenant,he was the leader and tudor was his lieutenant,he was the leader and tudor was his lieutenant,0.000000,0.000000,0.000000
6,arctic_b0237,SVBI,Hindi,They just lay off in the bush and plugged away,they just lay off in the bush and plucked away,they just lay off in the bush and plucked away,0.100000,0.100000,0.000000
7,arctic_b0236,SVBI,Hindi,Oolong was two hundred and fifty miles from the nearest land,oolong was 250 miles from the nearest land,oolong was 250 miles from the nearest land,0.363636,0.363636,0.000000
8,arctic_b0203,SVBI,Hindi,A month in Australia would finish me,a month in australia would finish me,a month in australia would finish me,0.000000,0.000000,0.000000
9,arctic_b0202,SVBI,Hindi,Society is shaken to its foundations,society is shaken to its foundations,society is shaken to its foundations,0.000000,0.000000,0.000000
10,arctic_b0201,SVBI,Hindi,I also understand that similar branch organizations have made their appearan...,i also understand that similar brand organizations have made their appearanc...,i also understand that similar brand organizations have made their appearanc...,0.076923,0.076923,0.000000
11,arctic_b0200,SVBI,Hindi,We leave the eventuality to time and law,we leave the eventuality to time and law,we leave the eventuality to time and law,0.000000,0.000000,0.000000
12,arctic_b0199,SVBI,Hindi,Dear Sir Your second victim has fallen on schedule time,dear sir your second victim has fallen on schedule time,dear sir your second victim has fallen on schedule time,0.000000,0.000000,0.000000
13,arctic_b0198,SVBI,Hindi,I use great trouble advisedly,i use great trouble advisedly,i use great trouble advisedly,0.000000,0.000000,0.000000
14,arctic_b0197,SVBI,Hindi,The planters are already considering the matter,the planters are already considering the matter,the planters are already considering the matter,0.000000,0.000000,0.000000
15,arctic_b0196,SVBI,Hindi,How can you manage all alone Mister Young,how can you manage all alone mr young,how can you manage all alone mr young,0.125000,0.125000,0.000000
16,arctic_b0195,SVBI,Hindi,Nobody knows how the natives got them,nobody knows how the natives got them,nobody knows how the natives got them,0.000000,0.000000,0.000000
17,arctic_b0194,SVBI,Hindi,Joan cried with shining eyes,john cradd with shining eyes,john cradd with shining eyes,0.400000,0.400000,0.000000
18,arctic_b0193,SVBI,Hindi,So was Packard's finish suicide,so was picards finnish suicide,so was picards finnish suicide,0.400000,0.400000,0.000000
19,arctic_b0192,SVBI,Hindi,Outsiders are allowed five minute speeches the sick man urged,outsiders have allowed 5 minute speeches the sick man urged,outsiders have allowed 5 minute speeches the sick man urged,0.200000,0.200000,0.000000

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0336,EBVS,Spanish,So unexpected was my charge that I knocked him off his feet,so unexpected was my charge that i knocked him off his feet,so unexpected was my charge that iron noct him of his feet,0.000000,0.250000,0.250000
1,arctic_b0285,EBVS,Spanish,The hyena proceeded to dine,the haviena proceeded to die,the haviena proceeded fine,0.400000,0.600000,0.200000
2,arctic_b0422,BDL,English,This was when the explosion occurred.,this was when the explosion occurred,but this was when the explosion occurred,0.000000,0.166667,0.166667
3,arctic_a0131,EBVS,Spanish,Providence had delivered him through the maelstrom,providence has delivered him through the mollestrone,providence has delivered him through the mothers throne,0.285714,0.428571,0.142857
4,arctic_a0593,HQTV,Vietnamese,She'd make a good wife for the cashier,she made a good wife for the cashier,she made a good wife for the katsuya,0.250000,0.375000,0.125000
5,arctic_a0276,HQTV,Vietnamese,Oolong Atoll was one hundred and forty miles in circumference,olong atoll was 140 miles in circumference,olong otorn was 140 miles in circumference,0.500000,0.600000,0.100000
6,arctic_a0588,EBVS,Spanish,He had proved it today with his amateurish and sophomoric productions,he had proved it today with his amateurish and softworking productions,he had proved it today with his amateurish and so forthmick productions,0.090909,0.181818,0.090909
7,arctic_a0566,ZHAA,Arabic,Dennin's hands were released long enough for him to sign the document,dinez hands were released long enough for him to sign the document,dinez hans were released long enough for him to sign the document,0.083333,0.166667,0.083333
8,arctic_a0084,HJK,Korean,Scarcely had he uttered the name when Pierre's closing eyes shot open,scarcely had he uttered the name when paris closing eyes shot open,scarcely had he uttered the name when paris closing eyes shut open,0.083333,0.166667,0.083333
9,arctic_a0410,SVBI,Hindi,So we have to fit the boat throughout with oil lamps as well,so we have to fit the boat throat with oil lamps as well,so we have to fit the boat through it with oil lamps as well,0.076923,0.153846,0.076923
10,arctic_b0206,SVBI,Hindi,Horses and rifles had been her toys camp and trail her nursery,horses and rifles had been her toys camp and trail her nursery,horses and rifles had been her toys camp and trail her nursery,0.000000,0.000000,0.000000
11,arctic_b0208,SVBI,Hindi,You read the quotations in today's paper,you read the quotations in todays paper,you read the quotations in todays paper,0.000000,0.000000,0.000000
12,arctic_b0209,SVBI,Hindi,He's terribly touchy about his black wards as he calls them,he is terribly touchy about his black warts as he calls them,he is terribly touchy about his black warts as he calls them,0.272727,0.272727,0.000000
13,arctic_b0210,SVBI,Hindi,Whatever he guessed he locked away in the taboo room of Naomi,whatever he guessed he locked away in the taboo room of naomi,whatever he guessed he locked away in the taboo room of naomi,0.000000,0.000000,0.000000
14,arctic_b0179,SVBI,Hindi,Let them go out and eat with my boys,let them go out and eat with my boys,let them go out and eat with my boys,0.000000,0.000000,0.000000
15,arctic_b0212,SVBI,Hindi,Death is and has been ever since old Maui died,death is and has been ever since old maui died,death is and has been ever since old maui died,0.000000,0.000000,0.000000
16,arctic_b0213,SVBI,Hindi,Some boy she laughed acquiescence,some boy she loved acquiescence,some boy she loved acquiescence,0.200000,0.200000,0.000000
17,arctic_b0214,SVBI,Hindi,Let us talk it over and find a way out,let us stock it over and find a way out,let us stock it over and find a way out,0.100000,0.100000,0.000000
18,arctic_b0215,SVBI,Hindi,It is a good property and worth more than that,it is a good property and worth more than that,it is a good property and worth more than that,0.000000,0.000000,0.000000
19,arctic_b0216,SVBI,Hindi,I wish you were more adaptable Joan retorted,i wish you were more adaptable johan retorted,i wish you were more adaptable johan retorted,0.125000,0.125000,0.000000

## bridge_dtw_fixed_x0_0.5

Utterances compared: 7796
  wins   (model better than baseline):   982  (12.60%)
  draws  (tied):                        5423  (69.56%)
  losses (model worse than baseline):   1390  (17.83%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          0.2232         0.0924
Chinese     1130            0.2010          0.4681         0.2671
English     1132            0.0402          0.0389        -0.0014
Hindi       1132            0.0708          0.0705        -0.0003
Korean      1131            0.0855          0.1082         0.0227
Spanish     1007            0.2364          0.7797         0.5433
Vietnamese  1132            0.3223          1.2862         0.9639

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0346,EBVS,Spanish,Get down and dig in,good town auntie king,get down and dig in,1.000000,0.000000,-1.000000
1,arctic_a0589,BWC,Chinese,I was sick once typhoid,i will seek once time for it,i was sick once typhoid,1.000000,0.000000,-1.000000
2,arctic_b0425,BDL,English,"There were orange-green, gold-green, and a copper-green.",there were orange green gold green and a copper green,there were orangegreen goldgreen and a coppergreen,0.857143,0.000000,-0.857143
3,arctic_b0354,HQTV,Vietnamese,It's that much junk,is that mcchunk,its that much junk,0.750000,0.000000,-0.750000
4,arctic_b0207,ZHAA,Arabic,I'm as good as a man she urged,amasgut ezaman she urged,im as good as a man she urged,0.750000,0.000000,-0.750000
5,arctic_b0257,HQTV,Vietnamese,Tudor surveyed him with withering disgust,to the survey he was with three discussed,to the survey him with withering disgust,1.166667,0.500000,-0.666667
6,arctic_a0381,SVBI,Hindi,My name's Ferguson,my name is fargusson,my names fergusson,1.000000,0.333333,-0.666667
7,arctic_b0299,HQTV,Vietnamese,Miss Brodie's smile was slightly sarcastic,misbroadies my words like this sarcastic,miss brodys smile was slightly sarcastic,0.833333,0.166667,-0.666667
8,arctic_b0436,HQTV,Vietnamese,Famine had been my great ally,famed has been migrated alive,femme had been my great ally,0.833333,0.166667,-0.666667
9,arctic_a0381,HJK,Korean,My name's Ferguson,my name is ferguson,my names ferguson,0.666667,0.000000,-0.666667
10,arctic_b0218,EBVS,Spanish,The issue was not in doubt,the issue was not in the up to date,the issue was not in doubt,0.666667,0.000000,-0.666667
11,arctic_a0389,BWC,Chinese,Mab she said,mab shes sad,mab she said,0.666667,0.000000,-0.666667
12,arctic_b0166,ZHAA,Arabic,Fast but endure,fast buttontoer,fast but endure,0.666667,0.000000,-0.666667
13,arctic_a0470,HQTV,Vietnamese,He spat it out like so much venom,his body down lies so much in the numb,his body out like so much venom,1.000000,0.375000,-0.625000
14,arctic_a0396,EBVS,Spanish,A rising tide of fat had submerged them,a racing title had so much time,a racing tide of hot had submerged them,0.875000,0.250000,-0.625000
15,arctic_b0221,EBVS,Spanish,It's a Yankee Joan cried,its sayankee john crite,its a yankee john cried,0.800000,0.200000,-0.600000
16,arctic_a0155,HQTV,Vietnamese,Won't you draw up gentlemen,one youve rarred and the other youve chandlemen,one youve wrought up in chandlerman,1.600000,1.000000,-0.600000
17,arctic_a0589,HJK,Korean,I was sick once typhoid,i was sick once time for it,i was sick once typhoid,0.600000,0.000000,-0.600000
18,arctic_b0325,BWC,Chinese,It was a gigantic inadequacy,it was gigantic in adequacy,it was a gigantic inadequacy,0.600000,0.000000,-0.600000
19,arctic_b0079,HQTV,Vietnamese,The truth of it set Jeanne quivering,detroit stop is said to be a river ring,the choice of east said kenny weavering,1.285714,0.714286,-0.571429

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0541,HQTV,Vietnamese,The Warden with a quart of champagne,the warning with the words of champion,the warring with the war of the world of the world of the world of the world...,0.571429,62.857143,62.285714
1,arctic_b0339,BWC,Chinese,Well I'll be plumb gosh darned,where ill be planned costumed,ill be planned and ill be planned and ill be planned and ill be planned and ...,0.666667,58.833333,58.166667
2,arctic_b0325,HQTV,Vietnamese,It was a gigantic inadequacy,its got a gigantic and other crazy,its whats called a gigantic and its whats called a gigantic and its whats ca...,1.000000,58.800000,57.800000
3,arctic_a0481,EBVS,Spanish,Nimrod replied with a slight manifestation of sensitiveness,nimrod replied with the lies manifestation of sensitiveness,nimrod replied with the light of the light of the light of the light of the ...,0.250000,54.875000,54.625000
4,arctic_a0352,HQTV,Vietnamese,I'm sure going along with you all Elijah,im sure going along with you all alisha,im sure going along with you all along with you all along with you all along...,0.125000,54.500000,54.375000
5,arctic_b0437,HQTV,Vietnamese,Nowhere in the North is the soil so prolific,nowhere in the north either soso or from leific,no where in the north it is so so so so so so so so so so so so so so so so ...,0.555556,48.777778,48.222222
6,arctic_a0468,HQTV,Vietnamese,In the matter of curry she is a sheer genius,it matters curry she is a chef genius,its the mother of the mother of the mother of the mother of the mother of th...,0.500000,44.100000,43.600000
7,arctic_b0539,HQTV,Vietnamese,You were making them talk shop Ruth charged him,you are making them the talk shop good chance him,you were making them the talk shop you were making them the talk shop you we...,0.444444,42.555556,42.111111
8,arctic_a0510,HQTV,Vietnamese,Much more Ernest told them of themselves and of his disillusionment,much more only told them of themselves and of his delusionment,much more than the tone of the most of the most of the most of the most of t...,0.181818,40.000000,39.818182
9,arctic_a0061,HQTV,Vietnamese,Philip snatched at the letter which Gregson held out to him,phyllis snatched at the letter which cressen held out to him,phyllis natch at the letter with the letter of the letter of the letter of t...,0.181818,39.818182,39.636364
10,arctic_b0420,BWC,Chinese,On occasion on this traverse the Cape Verde Islands are raised,on occasion on this river the cablevaryed islands are riced,on occasion the cable of the island of the island of the island of the islan...,0.363636,39.909091,39.545455
11,arctic_a0092,EBVS,Spanish,He went down in midstream searching the shadows of both shores,he went down in mainstream searching the shadows of both shores,he went down in the mainstream searching the shadows of the shadows of the s...,0.090909,39.545455,39.454545
12,arctic_a0407,BWC,Chinese,Mercedes screamed cried laughed and manifested the chaotic abandonment of hy...,macedas cried laughed and manifested the chaos and abandonment of hysteria,mcc cried laughed and manifested the chaos of the chaos of the chaos of the ...,0.363636,39.454545,39.090909
13,arctic_a0560,BWC,Chinese,His mouth opened words shaped vainly on his lips,his mouth open was shaped finally on his lip,his mouth opened and his mouth opened wide his mouth opened wide his mouth o...,0.444444,39.111111,38.666667
14,arctic_b0387,HQTV,Vietnamese,It is merely the simple superlative,its merely the simple superlative,its merely the simple simple simple simple simple simple simple simple simpl...,0.333333,36.833333,36.500000
15,arctic_a0084,EBVS,Spanish,Scarcely had he uttered the name when Pierre's closing eyes shot open,scarly had he uttered the name where peerless closing eyes shut open,scarly had he had he had he had he had he had he had he had he had he had he...,0.333333,36.750000,36.416667
16,arctic_b0433,HQTV,Vietnamese,We are cooking on the coal stove and on the oil burners,we are cooking on the coast of and on the oil burner,we are cooking on the coast of the coast of the coast of the coast of the co...,0.250000,36.500000,36.250000
17,arctic_a0324,EBVS,Spanish,It was not Red Eye's way to forego revenge so easily,it was not a red eyes way to fair revenge so easily,it was not a great idea to use the word but it was a great idea to use the w...,0.181818,36.363636,36.181818
18,arctic_a0211,HQTV,Vietnamese,It drowned all sound that brute agony and death may have made,its from known sound died fruit a gunny and death may have met,its from the south a man who has been killed by a man who has been killed by...,0.666667,36.833333,36.166667
19,arctic_b0263,HQTV,Vietnamese,Only once did I confide the strangeness of it all to another,only one this i confide the strength of its own to another,only one i confide the strength of the strength of the strength of the stren...,0.416667,36.583333,36.166667

## bridge_dtw_fixed_x0_0.5_odesampling

Utterances compared: 7796
  wins   (model better than baseline):  1038  (13.31%)
  draws  (tied):                        5667  (72.69%)
  losses (model worse than baseline):   1090  (13.98%)

**By L1:**

               n  utt_wer_baseline  utt_wer_bridge  utt_wer_delta
l1
Arabic      1132            0.1308          0.1795         0.0487
Chinese     1130            0.2010          0.3103         0.1093
English     1132            0.0402          0.0378        -0.0024
Hindi       1132            0.0708          0.0655        -0.0053
Korean      1131            0.0855          0.0818        -0.0037
Spanish     1007            0.2364          0.6224         0.3860
Vietnamese  1132            0.3223          0.8412         0.5189

**Best wins — top 20 by `utt_wer` delta (model beats baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_a0589,BWC,Chinese,I was sick once typhoid,i will seek once time for it,i was sick once typhoid,1.000000,0.000000,-1.000000
1,arctic_a0381,SVBI,Hindi,My name's Ferguson,my name is fargusson,my names ferguson,1.000000,0.000000,-1.000000
2,arctic_b0425,BDL,English,"There were orange-green, gold-green, and a copper-green.",there were orange green gold green and a copper green,there were orangegreen goldgreen and a coppergreen,0.857143,0.000000,-0.857143
3,arctic_b0207,ZHAA,Arabic,I'm as good as a man she urged,amasgut ezaman she urged,im as good as a man she urged,0.750000,0.000000,-0.750000
4,arctic_b0299,HQTV,Vietnamese,Miss Brodie's smile was slightly sarcastic,misbroadies my words like this sarcastic,miss brodys smile was slightly sarcastic,0.833333,0.166667,-0.666667
5,arctic_a0381,HJK,Korean,My name's Ferguson,my name is ferguson,my names ferguson,0.666667,0.000000,-0.666667
6,arctic_b0166,ZHAA,Arabic,Fast but endure,fast buttontoer,fast but endure,0.666667,0.000000,-0.666667
7,arctic_a0389,BWC,Chinese,Mab she said,mab shes sad,mab she said,0.666667,0.000000,-0.666667
8,arctic_b0218,EBVS,Spanish,The issue was not in doubt,the issue was not in the up to date,the issue was not in doubt,0.666667,0.000000,-0.666667
9,arctic_a0155,HQTV,Vietnamese,Won't you draw up gentlemen,one youve rarred and the other youve chandlemen,one youve rarred in chanderman,1.600000,1.000000,-0.600000
10,arctic_b0128,SVBI,Hindi,Philip bent low over Pierre,philip bentlow over peer,philip bent low over pierre,0.600000,0.000000,-0.600000
11,arctic_a0589,HJK,Korean,I was sick once typhoid,i was sick once time for it,i was sick once typhoid,0.600000,0.000000,-0.600000
12,arctic_b0338,HQTV,Vietnamese,It was unobtrusive yet it was there,is there enough truth to see yes its there,it was an obstructive just as it was there,1.142857,0.571429,-0.571429
13,arctic_a0293,HJK,Korean,They were deep in the primeval forest,theyre deep in the prime of all forests,theyre deep in the primeval forest,0.857143,0.285714,-0.571429
14,arctic_a0119,HQTV,Vietnamese,Jeanne was turning the bow shoreward,genie would turn in the bull straw world,jeanne was turning the ball into a star,1.166667,0.666667,-0.500000
15,arctic_a0016,BWC,Chinese,There's Fort Churchill a rifle shot beyond the ridge asleep,there is a fourth chieftain a riff shot beyond the reach as a leap,theres fort chechel a reef shot beyond the ridge as a leap,1.000000,0.500000,-0.500000
16,arctic_b0257,BWC,Chinese,Tudor surveyed him with withering disgust,twitter surveyed him with a weathering discussed,tudor surveyed him with a withering disgust,0.666667,0.166667,-0.500000
17,arctic_b0354,EBVS,Spanish,It's that much junk,is that machank,is that much junk,0.750000,0.250000,-0.500000
18,arctic_b0262,SVBI,Hindi,Saxon's onto her job,saxons on to her job,saxons onto her job,0.500000,0.000000,-0.500000
19,arctic_a0150,BWC,Chinese,Goodbye Pierre he shouted,goodbye pr he shot it,goodbye piya he shouted,0.750000,0.250000,-0.500000

**Worst losses — top 20 by `utt_wer` delta (model loses to baseline most):**

,utterance_id,speaker,l1,text,prediction_norm_baseline,prediction_norm_bridge,utt_wer_baseline,utt_wer_bridge,utt_wer_delta
0,arctic_b0134,HQTV,Vietnamese,Blind with rage he darted in,life with earth he doubted in,life is a life that is not a life that is not a life that is not a life that...,0.500000,74.000000,73.500000
1,arctic_a0481,EBVS,Spanish,Nimrod replied with a slight manifestation of sensitiveness,nimrod replied with the lies manifestation of sensitiveness,nimrod replied with the light of the light of the light of the light of the ...,0.250000,54.875000,54.625000
2,arctic_b0437,HQTV,Vietnamese,Nowhere in the North is the soil so prolific,nowhere in the north either soso or from leific,no where in the north it is so so so so so so so so so so so so so so so so ...,0.555556,48.777778,48.222222
3,arctic_a0319,EBVS,Spanish,And the Edinburgh Evening News says with editorial gloom,and edimborn avenue news says with editorial groom,and the edinbauer news news news news news news news news news news news new...,0.444444,48.666667,48.222222
4,arctic_b0539,HQTV,Vietnamese,You were making them talk shop Ruth charged him,you are making them the talk shop good chance him,you were making them the talk shop you were making them the talk shop you we...,0.444444,42.555556,42.111111
5,arctic_a0263,HQTV,Vietnamese,Joan looked triumphantly at Sheldon who bowed,charm looked triumphantly as sheldon who bowed,sharn looked triumphantly as sharn looked triumphantly as sharn looked trium...,0.285714,42.000000,41.714286
6,arctic_a0503,BWC,Chinese,His beady black eyes saw bargains where other men saw bankruptcy,he beat the black eye saw blank knees where other men saw bankruptcy,he beaded black eyes of the black eye of the black eye of the black eye of t...,0.545455,40.090909,39.545455
7,arctic_a0407,BWC,Chinese,Mercedes screamed cried laughed and manifested the chaotic abandonment of hy...,macedas cried laughed and manifested the chaos and abandonment of hysteria,mcc cried laughed and manifested the chaos of the chaos of the chaos of the ...,0.363636,39.272727,38.909091
8,arctic_a0560,EBVS,Spanish,His mouth opened words shaped vainly on his lips,his mouth opened wore shaped vainly on his lips,his mouth opened and his mouth opened and his mouth opened and his mouth ope...,0.111111,39.000000,38.888889
9,arctic_a0202,EBVS,Spanish,She turned fearing that Jacques might see what was in her face,she turned it fairing that jax might see what was in her face,she turned and turned and turned and turned and turned and turned and turned...,0.250000,36.833333,36.583333
10,arctic_b0263,HQTV,Vietnamese,Only once did I confide the strangeness of it all to another,only one this i confide the strength of its own to another,only one i confide the strength of the strength of the strength of the stren...,0.416667,36.583333,36.166667
11,arctic_b0078,EBVS,Spanish,There was pride and strength the ring of triumph in his voice,there was pride of the strange the ring of strings in kid boys,there was pride in the strange ring of the stream of the stream of the strea...,0.500000,36.583333,36.083333
12,arctic_b0385,HQTV,Vietnamese,Last night he showed all the symptoms of coming down with pneumonia,last night he showed on the scene some of coming down with yunonia,last night he showed on the scene of coming to the scene of coming to the sc...,0.333333,36.416667,36.083333
13,arctic_a0269,ZHAA,Arabic,That's where they cut off the Scottish Chiefs and killed all hands,thats where they cut off these cutted chiefs and cut old hands,thats where they cut off the cut off the cut off the cut off the cut off the...,0.333333,36.416667,36.083333
14,arctic_a0305,HQTV,Vietnamese,They had no fixed values to be altered by adjectives and adverbs,i had no fixed value to be on to my objective and i was,i had no fixed value to be on my own to be on my own to be on my own to be o...,0.666667,36.583333,35.916667
15,arctic_b0402,EBVS,Spanish,An altruistic act is an act performed for the welfare of others,and altricicac is an apt performance for the welfare of others,an altruistic act is an act of act of act of act of act of act of act of act...,0.416667,36.250000,35.833333
16,arctic_a0543,HQTV,Vietnamese,I had been born with no organic chemical predisposition toward alcohol,i have been born with no organic chemistry school with this devotion to our ...,i have been born with no organic chemistry but i have been born with no orga...,0.818182,35.818182,35.000000
17,arctic_a0139,EBVS,Spanish,He told himself that as he washed himself and groomed his disheveled clothes,he told himself that as he washed himself and groomed his dishshell clothes,he told himself that as he watched himself and his own body he was the one w...,0.076923,33.461538,33.384615
18,arctic_a0186,HQTV,Vietnamese,Like a flash he launched himself into the feathered mass of the owl,like a flash he launched himself into the theater mass of the old,like a flash he launched himself into the theater of the theater of the thea...,0.153846,33.307692,33.153846
19,arctic_b0204,EBVS,Spanish,Down through the perfume weighted air fluttered the snowy fluffs of the cott...,the enter of the perfume waited i filtered the snowy floofs of the cotton goods,down through the perfumed wait i put the floating floating floating floating...,0.692308,33.769231,33.076923

In [27]:
# ── Look up specific utterances across all models ─────────────────────────────
# Add (utterance_id, speaker) pairs here to see how the baseline and every
# comparison model handled them, side by side.
LOOKUP_UTTERANCES = [
    ('arctic_a0484', 'BDL'),
    ('arctic_b0319', 'HQTV'),
]

lookup_keys = pd.DataFrame(LOOKUP_UTTERANCES, columns=['utterance_id', 'speaker'])

base_cols = ['utterance_id', 'speaker'] + (['l1'] if 'l1' in da_baseline.columns else []) + \
            ['text', 'prediction_norm', PRIMARY_METRIC]
wide = lookup_keys.merge(da_baseline[base_cols], on=['utterance_id', 'speaker'], how='left')
wide = wide.rename(columns={
    'prediction_norm': f'prediction_norm_{BASELINE}',
    PRIMARY_METRIC: f'{PRIMARY_METRIC}_{BASELINE}',
})

for r in results:
    sub = r['merged'][['utterance_id', 'speaker', 'prediction_norm_bridge', f'{PRIMARY_METRIC}_bridge']].rename(columns={
        'prediction_norm_bridge': f'prediction_norm_{r["name"]}',
        f'{PRIMARY_METRIC}_bridge': f'{PRIMARY_METRIC}_{r["name"]}',
    })
    wide = wide.merge(sub, on=['utterance_id', 'speaker'], how='left')

wide

,utterance_id,speaker,l1,text,prediction_norm_baseline:whisper,utt_wer_baseline:whisper,prediction_norm_bridge_dtw_eps_0.5,utt_wer_bridge_dtw_eps_0.5,prediction_norm_bridge_dtw_eps_0.5_odesampling,utt_wer_bridge_dtw_eps_0.5_odesampling,prediction_norm_bridge_position_eps_1.5,utt_wer_bridge_position_eps_1.5,prediction_norm_bridge_dtw_fixed_eps_0.5,utt_wer_bridge_dtw_fixed_eps_0.5,prediction_norm_bridge_dtw_fixed_eps_0.5_odesampling,utt_wer_bridge_dtw_fixed_eps_0.5_odesampling,prediction_norm_bridge_dtw_fixed_x0_0.5,utt_wer_bridge_dtw_fixed_x0_0.5,prediction_norm_bridge_dtw_fixed_x0_0.5_odesampling,utt_wer_bridge_dtw_fixed_x0_0.5_odesampling
0,arctic_a0484,BDL,English,No-sir-ee.,no surrey,2.0,no sirree,2.0,no sir re,3.0,no siri,2.0,no surrey,2.0,no surrey,2.0,no sirree,2.0,no surrey,2.0
1,arctic_b0319,HQTV,Vietnamese,Daylight was tired profoundly tired,they lied to a tire a foully tire,1.6,they lied were tired profoundly tired,0.6,they lied to a tire a foully tire,1.6,they lie lie lie lie lie lie lie lie lie lie lie lie lie lie lie lie lie lie...,44.6,they lied were tired were fowlly tired,1.0,they lied to a tire a foully tire,1.6,they lied to the tyrant and they were tired,1.6,they lied were tied refowlied tied,1.2